原文地址

1.为什么要处理异常
用户体验
远程定位问题；
未雨绸缪，及早发现问题；
无法复线问题，尤其是移动端，机型，系统都是问题；
完善的前端方案，前端监控系统；
对于 Javascript 而言，我们面对的仅仅只是异常，异常的出现不会直接导致 JS 引擎崩溃，最多只会使当前执行的任务终止。


2.需要监控哪些？
我们要捕获的异常和反馈大致如下：
-js错误
-ajax请求异常
-静态资源加载异常
-promise异常
-iframe 异常
-崩溃和卡顿
3.Try-Catch的误区
try-catch 只能捕获到同步的运行时错误，对语法和异步错误却无能为力，捕获不到。
-同步运行时错误：


try {
  let name = 'jartto';
  console.log(nam);  
} catch(e) {
  console.log('捕获到异常：',e);
}


输出：
 
捕获到异常： ReferenceError: nam is not defined
    at <anonymous>:3:15
 

-不能捕获到语法错误，我们修改一下代码，删掉一个单引号：
 
try {
  let name = 'jartto;
  console.log(nam);  
} catch(e) {
  console.log('捕获到异常：',e);
}
 
输出：


Uncaught SyntaxError: Invalid or unexpected token


不过语法错误在我们开发阶段就可以看到，应该不会顺利上到线上环境。
-异步错误
 
try {
setTimeout(() => {
undefined.map(v => v);
}, 1000)
} catch(e) {
console.log('捕获到异常：',e);
}
 
我们看看日志：
 
Uncaught TypeError: Cannot read property 'map' of undefined
    at setTimeout (<anonymous>:3:11)
 
并没有捕获到异常，这是需要我们特别注意的地方。
4.window.onerror 不是万能的
当JavaScript运行时错误发生时，window会触发一个ErrorEvent接口的error事件，并执行window.onerror()。


/**
* @param {String}  message    错误信息
* @param {String}  source    出错文件
* @param {Number}  lineno    行号
* @param {Number}  colno    列号
* @param {Object}  error  Error对象（对象）
*/

window.onerror = function(message, source, lineno, colno, error) {
   console.log('捕获到异常：',{message, source, lineno, colno, error});
}


-首先试试同步运行时错误


window.onerror = function(message, source, lineno, colno, error) {
// message：错误信息（字符串）。
// source：发生错误的脚本URL（字符串）
// lineno：发生错误的行号（数字）
// colno：发生错误的列号（数字）
// error：Error对象（对象）
console.log('捕获到异常：',{message, source, lineno, colno, error});
}
Jartto;


可以看到，我们捕获到了异常：
17zuoye 研发 > 7.优雅处理前端异常 > image2018-11-22 15:44:43.png
-再试试语法错误呢？
 
window.onerror = function(message, source, lineno, colno, error) {
console.log('捕获到异常：',{message, source, lineno, colno, error});
}
let name = 'Jartto
 
控制台打印出了这样的异常：


Uncaught SyntaxError: Invalid or unexpected token


什么，竟然没有捕获到语法错误？
-怀着忐忑的心，我们最后来试试异步运行时错误：
 
window.onerror = function(message, source, lineno, colno, error) {
    console.log('捕获到异常：',{message, source, lineno, colno, error});
}
setTimeout(() => {
    Jartto;
});
 
控制台输出了：
 
捕获到异常： {message: "Uncaught ReferenceError: jartto is not defined", source: "http://127.0.0.1:8001/", lineno: 36, colno: 5, error: ReferenceError: jartto is not defined
    at setTimeout (http://127.0.0.1:8001/:36:5)}
 
-接着，我们试试网络请求异常的情况：
 
<script>
window.onerror = function(message, source, lineno, colno, error) {
    console.log('捕获到异常：',{message, source, lineno, colno, error});
    return true;
}
</script>
<img src="./jartto.png">
 
我们发现，不论是静态资源异常，或者接口异常，错误都无法捕获到。
补充一点：window.onerror 函数只有在返回 true 的时候，异常才不会向上抛出，否则即使是知道异常的发生控制台还是会显示 Uncaught Error: xxxxx。
 
window.onerror = function(message, source, lineno, colno, error) {
    console.log('捕获到异常：',{message, source, lineno, colno, error});
    return true;
}
setTimeout(() => {
    Jartto;
});
 
控制台就不会再有这样的错误了：
 
Uncaught ReferenceError: jartto is not defined
    at setTimeout ((index):36)
 
需要注意：
onerror最好写在所有 JS 脚本的前面，否则有可能捕获不到错误
onerror无法捕获语法错误
到这里基本就清晰了：
在实际的使用过程中，onerror 主要是来捕获预料之外的错误，而 try-catch 则是用来在可预见情况下监控特定的错误，两者结合使用更加高效。
问题又来了，捕获不到静态资源加载异常怎么办？
5.window.addEventListener 
当一项资源（如图片或脚本）加载失败，加载资源的元素会触发一个Event接口的error事件，并执行该元素上的onerror()处理函数。这些error事件不会向上冒泡到window，不过（至少在Firefox中）能被单一的window.addEventListener捕获。
 
<scritp>
window.addEventListener('error', (error) => {
    console.log('捕获到异常：', error);
}, true)
</script>
<img src="./jartto.png">
 
控制台输出：
17zuoye 研发 > 7.优雅处理前端异常 > image2018-11-22 15:48:12.png
由于网络请求异常不会事件冒泡，因此必须在捕获阶段将其捕捉到才行，但是这种方式虽然可以捕捉到网络请求的异常，但是无法判断 HTTP 的状态是 404 还是其他比如 500 等等，所以还需要配合服务端日志才进行排查分析才可以。
需要注意：
-不同浏览器下返回的error对象可能不同，需要注意兼容处理。
-需要注意避免addEventListener重复监听。
6.Promise Catch
在promise中使用catch可以非常方便的捕获到异步error，这个很简单。
没有写catch的Promise中抛出的错误无法被onerror 或 try-catch捕获到，所以我们务必要在Promise中不要忘记写catch处理抛出的异常。
解决方案： 为了防止有漏掉的Promise异常，建议在全局增加一个对unhandledrejection的监听，用来全局监听Uncaught Promise Error。使用方式：
 
window.addEventListener("unhandledrejection", function(e){
        console.log(e);
});


我们继续来尝试一下：
 
window.addEventListener("unhandledrejection", function(e){
  e.preventDefault()
  console.log('捕获到异常：', e);
  return true;
});
Promise.reject('promise error');
 
可以看到如下输出：
17zuoye 研发 > 7.优雅处理前端异常 > image2018-11-22 15:49:26.png
那如果对 Promise 不进行 catch 呢？
 
window.addEventListener("unhandledrejection", function(e){
  e.preventDefault()
  console.log('捕获到异常：', e);
  return true;
});
new Promise((resolve, reject) => {
  reject('jartto: promise error');
});
 
嗯，事实证明，也是会被正常捕获到的。
所以，正如我们上面所说，为了防止有漏掉的Promise异常，建议在全局增加一个对unhandledrejection的监听，用来全局监听Uncaught Promise Error。
7.VUE errorHandler
 
Vue.config.errorHandler = (err, vm, info) => {
  console.error('通过vue errorHandler捕获的错误');
  console.error(err);
  console.error(vm);
  console.error(info);
}


8.React 异常捕获
React 16 提供了一个内置函数 componentDidCatch，使用它可以非常简单的获取到 react 下的错误信息
componentDidCatch(error, info) { 
    console.log(error, info);
}
 
9.iframe 异常
 
window.onerror = function(message, source, lineno, colno, error) {
    console.log('捕获到异常：',{message, source, lineno, colno, error});
}
<iframe src="./iframe.html" frameborder="0"></iframe>
<script>
  window.frames[0].onerror = function (msg, url, row, col, error) {
    console.log('我知道 iframe 的错误了，也知道错误信息');
    console.log({
      msg,  url,  row, col, error
    })
    return true;
  };
</script>
 
10.崩溃和卡顿
https://juejin.im/entry/5be158116fb9a049c6434f4a?utm_source=gold_browser_extension
卡顿也就是网页暂时响应比较慢，JS 可能无法及时执行，这也是上篇网页卡顿监控所依赖的技术点。
但崩溃就不一样了，网页都崩溃了，页面看不见了，JS 都不运行了，还有什么办法可以监控网页的崩溃，并将网页崩溃上报呢？
11.错误上报
-通过 Ajax 发送数据
因为Ajax请求本身也有可能会发生异常，而且有可能会引发跨域问题，一般情况下更推荐使用动态创建img标签的形式进行上报。
-动态创建 img 标签的形式
实例 - 动态创建 img 标签进行上报
function report(error) {
  var reportUrl = 'http://xxxx/report';
  new Image().src = reportUrl + 'error=' + error;
}
收集异常信息量太多，怎么办？如果你的网站访问量很大，假如网页的 PV 有 1kw，那么一个必然的错误发送的信息就有 1kw 条，我们可以给网站设置一个采集率：
Reporter.send = function(data) {
  // 只采集 30%
  if(Math.random() < 0.3) {
    send(data)      // 上报错误信息
  }
}
这个采集率可以通过具体实际的情况来设定，方法多样化，可以使用一个随机数，也可以具体根据用户的某些特征来进行判定。